### PR TITLE
Small refactor for the routes file

### PR DESCRIPTION
**Pull request by noamokman**
Hi there,
Just wanted to suggest this way of handling the excess to the express app from the routes file.
I made the routes file expose a function that accepts the express app.
Therefore we can avoid this line:
```js
var app = module.parent.exports.app;
```

### CODE REVIEW

**Comment by samccone** [comment]
:clap: so much better thanks @noamokman

**Comment by noamokman** [comment]
Happy to help :+1:

**Comment by noamokman** [comment]
any reason this isn't merged in yet?

**Comment by noamokman** [comment]
updated branch to prevent merge confilcts

**Comment by sheerun** [comment]
Rebased and merged to master. Thank you

**Pull request closed without merging**
